version: '3.8'

services:
  # --- Serviços de Banco de Dados PostgreSQL ---
  users-db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "users_db"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - chego-network

  orders-db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" 
    volumes:
      - orders_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "orders_db"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - chego-network

  pricing-db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" 
    volumes:
      - pricing_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "pricing_db"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - chego-network

  # --- Serviço de Mensageria RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

    networks:
      - chego-network

  # --- Seus Serviços de Aplicação ---
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      USER_SERVICE_URL: users-service:50051
      PRICING_SERVICE_URL: pricing-service:50052
      ORDER_SERVICE_URL: order-service:50053
      JWT_SECRET: JWT_SECRETtestetete
      PORT: 9000
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    depends_on:
      - order-service
      - users-service
      - pricing-service
      - rabbitmq
    networks:
      - chego-network

  users-service:
    build:
      context: . # Contexto na raiz do projeto para acessar o diretório proto
      dockerfile: users-service/Dockerfile
    ports:
      - "50051:50051" # Porta gRPC padrão do Users Service
      - "9001:9001" # Porta HTTP padrão do Users Service
    environment:
      DATABASE_URL: postgresql://user:password@users-db:5432/users_db?schema=public
      JWT_SECRET: JWT_SECRETtestetete
      RABBITMQ_QUEUE: user_events_queue
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      METRICS_PORT: 9001
    depends_on:
      rabbitmq:
        condition: service_healthy
      users-db:
        condition: service_healthy
    networks:
      - chego-network

  pricing-service:
    build:
      context: .
      dockerfile: pricing-service/Dockerfile
    ports:
      - "50052:50052"
      - "9002:9002"
    environment:
      DATABASE_URL: postgresql://user:password@pricing-db:5432/pricing_db?schema=public
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      METRICS_PORT: 9002
    depends_on:
      pricing-db:
        condition: service_healthy
    networks:
      - chego-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "50053:50053"
      - "9003:9003"
    environment:
      DATABASE_URL: postgresql://user:password@orders-db:5432/orders_db?schema=public
      RABBITMQ_QUEUE: order_events_queue
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      METRICS_PORT: 9003
    depends_on:
      rabbitmq:
        condition: service_healthy
      orders-db:
        condition: service_healthy
    networks:
      - chego-network

  # --- Serviços de Monitoramento ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Porta da UI do Prometheus
    volumes:
      # Caminho relativo ao docker-compose.yml principal, para o arquivo prometheus.yml
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    depends_on:
      - api-gateway # Prometeus precisa do API Gateway para coletar métricas HTTP
      - users-service # Prometeus precisará dos microserviços (via exporters)
      - pricing-service # Prometeus precisará dos microserviços (via exporters)
    networks:
      - chego-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - chego-network

# --- Volumes Persistentes ---
volumes:
  users_data:
  orders_data:
  pricing_data:
  grafana_data: # Adicione o volume para persistência do Grafana

# --- Redes ---
networks:
  chego-network:
    driver: bridge